# Generated by Django 2.2.5 on 2019-12-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrs', '0002_subject_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('email', models.CharField(max_length=35, verbose_name='邮箱')),
                ('tel', models.IntegerField(max_length=20, verbose_name='电话')),
                ('regdate', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name_plural': '用户',
                'db_table': 'tb_user',
            },
        ),
    ]
